language: python

sudo: false

dist: trusty

python:
- '3.5'
- '3.6'

os:
- linux

install:
  - pip install coveralls
  - pip install coverage
  - pip install pylint
  - pip install -r test_requirements.txt

script:
  - python -m unittest discover
  - python -m coverage run --branch --source . -m unittest discover --verbose

after_success:
  - python -m coverage report --show-missing
  - coveralls
