language: python

sudo: false

dist: trusty

python:
- '3.4'
- '3.6'

os:
- linux

script:
  - python -m unittest discover

after_success:
  - python -m pylint --load-plugins=pylint.extensions.mccabe --docstring-min-length 5 --no-docstring-rgx "^(test)?_|.*Tests$" --unsafe-load-any-extension y --output-format colorized  --reports y $(find . -name "*.py")
  - python -m coverage report --show-missing
  - coveralls
