language: python

sudo: false

dist: trusty

python:
- '3.6'

os:
- linux

install:
  - pip install coveralls
  - pip install coverage
  - pip install pylint
  - pip install -r test_requirements.txt

before_script: # configure a headless display to test plot generation
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - python -m coverage run --source . -m unittest discover --verbose
  - PYTHONPATH=./ find ./examples/ -name "*.py" -exec python3 -m coverage run --append --source . {} \;

after_success:
  - python -m coverage report --show-missing
  - coveralls
